language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
script: phpunit --stderr --configuration phpunit.xml --coverage-text
matrix:
  fast_finish: true
  allow_failures:
    - php: 
      -nightly
      - '5.3'
      - '5.4'
