language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
script: phpunit --bootstrap tests/bootstap.php tests/
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly